[package]
name = "wait_not_await"
version = "0.2.1"
description = "Simple awaiter implementation"
authors = ["Nikita Podvirnyy <suimin.tu.mu.ga.mi@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/krypt0nn/wait_not_await"
edition = "2021"
